name: Sync with upstream

on:
  schedule:
    - cron: '0 0 * * 0'  # 每周日 UTC 0点运行
  workflow_dispatch:     # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: master
        
    - name: Setup Git
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        
    - name: Add upstream
      run: |
        git remote add upstream https://github.com/prometheus/node_exporter.git
        git fetch upstream
        
    - name: Sync with upstream
      run: |
        git checkout master
        git merge upstream/master
        git push origin master
